/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src.test.java.smile.identity.core;

import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.junit.Before;
import org.junit.Test;

public class WebApiTest {
	
    private String PARTNER_ID = "<PARTNER_ID>";
    private String API_KEY = "<API_KEY>";
    private Signature mSignature;
    private WebApi mWebApi;
    private MockWebServer mMockServer = null;
    private MockResponse mMockResponse = null;
	
    @Before
    public void setup() {
        mMockServer = new MockWebServer();
        mMockServer.start(PORT);
        mMockResponse = new MockResponse();
        
    	mSignature = new Signature(PARTNER_ID, API_KEY);
    	mWebApi = new WebApi(PARTNER_ID, "", API_KEY, "0");
    }

    @Test
    public void testWebToken() {
    	String tokenResponse = "{\"success\":true,\"token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXJ0bmVyX3BhcmFtcyI6eyJ1c2VyX2lkIjoiZTFkNDZkZTYtM2NjOS00MDMyLWI3ZjEtZDRlNGViZTNlMWFhIiwiam9iX2lkIjoiNDBmYjNlN2MtMjlmZS00YjRlLTlhNTAtOGE2MzI4YmU5OTY2Iiwiam9iX3R5cGUiOjJ9LCJjYWxsYmFja191cmwiOiJodHRwczovL3Rlc3Qtc21pbGVpZC5oZXJva3VhcHAuY29tL2FwaS92Mi8xMDQ2L3Bvc3RiYWNrL3VwZGF0ZV9zdGF0dXMvIiwiaWF0IjoxNjMwNjg2MTAxLCJleHAiOjE2MzIzMTY3ODB9.GBgrp8K0LsJor6lGPGZNdTVfC9KDXDsCDUAmOR3Hqgw\"}";
    	JSONObject response = (JSONObject) new JSONParser().parse(tokenResponse);
    	
    	mMockResponse.setResponseCode(200);
        mMockResponse.setBody(response.toJSONString());
        mMockServer.enqueue(mMockResponse);
    	
    	mWebApi.get_web_token(null, PARTNER_ID, PARTNER_ID, 0, API_KEY);
    }
}